// Code generated by protoc-gen-wasmify-go. DO NOT EDIT.

package internal

import (
	"encoding/binary"
	"errors"
	"fmt"
	"math"
	"os"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"

	"github.com/goccy/pythonwasm2go"
	"github.com/goccy/pythonwasm2go/base"
)

var (
	_ = binary.LittleEndian
	_ = errors.New
	_ = fmt.Errorf
	_ = math.Float32bits
	_ = os.Stderr
	_ = runtime.SetFinalizer
	_ = sort.Search
	_ = strconv.Itoa
	_ = strings.TrimSpace
	_ = sync.Once{}
	_ = wasm2go.Memory
	_ *base.Module
)

// pbNewBuf returns the scratch buffer every request marshal starts
// from. Starting from a presized slice instead of nil removes the
// append growth ladder (nil→8→16→… reallocations plus copies) that
// made runtime.growslice-under-pbAppendVarint 90% of one hot
// consumer's slice-growth profile; 64 bytes covers the dominant
// single-handle request shape (≤ 13 bytes) and small argument
// messages in one allocation. A sync.Pool variant was measured and
// REJECTED: the per-call Get/Put traffic and the pointer box each
// Put allocates cost more time than the saved reallocations
// (isolated A/B on googlesqlite's window suite: allocs/op −15% but
// sec/op +1.5%, B/op +4.8%).
func pbNewBuf() []byte { return make([]byte, 0, 64) }

// pbVarintLen reports the encoded size of v without writing it.
func pbVarintLen(v uint64) int {
	n := 1
	for v >= 0x80 {
		v >>= 7
		n++
	}
	return n
}

// pbAppendVarint appends a varint-encoded uint64.
func pbAppendVarint(buf []byte, v uint64) []byte {
	for v >= 0x80 {
		buf = append(buf, byte(v)|0x80)
		v >>= 7
	}
	return append(buf, byte(v))
}

// pbAppendTag appends a field tag.
func pbAppendTag(buf []byte, field, wireType uint32) []byte {
	return pbAppendVarint(buf, uint64(field<<3|wireType))
}

func pbAppendUint64(buf []byte, field uint32, v uint64) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, v)
}

func pbAppendInt32(buf []byte, field uint32, v int32) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, uint64(v))
}

func pbAppendInt64(buf []byte, field uint32, v int64) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, uint64(v))
}

func pbAppendBool(buf []byte, field uint32, v bool) []byte {
	buf = pbAppendTag(buf, field, 0)
	if v {
		return append(buf, 1)
	}
	return append(buf, 0)
}

func pbAppendString(buf []byte, field uint32, s string) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(s)))
	return append(buf, s...)
}

func pbAppendBytes(buf []byte, field uint32, data []byte) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(data)))
	return append(buf, data...)
}

func pbAppendFloat(buf []byte, field uint32, v float32) []byte {
	buf = pbAppendTag(buf, field, 5)
	var tmp [4]byte
	binary.LittleEndian.PutUint32(tmp[:], math.Float32bits(v))
	return append(buf, tmp[:]...)
}

func pbAppendDouble(buf []byte, field uint32, v float64) []byte {
	buf = pbAppendTag(buf, field, 1)
	var tmp [8]byte
	binary.LittleEndian.PutUint64(tmp[:], math.Float64bits(v))
	return append(buf, tmp[:]...)
}

func pbAppendSubmessage(buf []byte, field uint32, sub []byte) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(sub)))
	return append(buf, sub...)
}

func pbAppendHandle(buf []byte, field uint32, ptr uint64) []byte {
	// The submessage has a fixed shape — tag(1,varint) + varint(ptr),
	// ≤ 11 bytes — so its length is computable up front and the
	// whole thing can be written straight into buf. The previous
	// shape built the inner bytes in a fresh slice per call
	// (`pbAppendUint64(nil, …)`), one heap allocation per handle
	// field on every bridge call.
	inner := 1 + pbVarintLen(ptr)
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(inner))
	buf = append(buf, 0x08) // field 1, wire type varint
	return pbAppendVarint(buf, ptr)
}

// pbAppendHandlePtr is the nil-safe one-line wrapper around
// pbAppendHandle. Generic + comparable lets it accept any
// pointer-typed wrapper that provides rawPtr() and short-circuit
// when the pointer is nil. The caller writes
//
//	buf = pbAppendHandlePtr(buf, N, v.X)
//
// which gofmt keeps as one line; the alternative
//
//	if v.X != nil { buf = pbAppendHandle(buf, N, v.X.rawPtr()) }
//
// is gofmt-expanded to three lines per occurrence and accounts
// for several hundred KB of bloat across the binding.
func pbAppendHandlePtr[T interface {
	comparable
	rawPtr() uint64
}](buf []byte, field uint32, v T) []byte {
	var zero T
	if v == zero {
		return buf
	}
	return pbAppendHandle(buf, field, v.rawPtr())
}

// pbAppendSubmessagePtr is the value-type-message counterpart of
// pbAppendHandlePtr: nil-safe, gofmt-friendly one-liner around
// pbAppendSubmessage + the type's marshal() helper.
func pbAppendSubmessagePtr[T interface {
	comparable
	marshal() []byte
}](buf []byte, field uint32, v T) []byte {
	var zero T
	if v == zero {
		return buf
	}
	return pbAppendSubmessage(buf, field, v.marshal())
}

// clearPtrAny is the gofmt-friendly nil-safe ownership-transfer
// helper for handle parameters. Replaces the inline expansion
//
//	if c, ok := v.(interface{ clearPtr() }); ok { c.clearPtr() }
//
// (3 lines after gofmt) plus its surrounding nil-guard with a
// single function call. Handles both interface values
// (CatalogNode et al) and concrete pointers; the type assertion
// short-circuits when v is a true-nil interface, and the wrapped
// clearPtr() is itself nil-receiver-safe so a typed-nil pointer
// passed through the interface no-ops cleanly.
func clearPtrAny(v any) {
	if c, ok := v.(interface{ clearPtr() }); ok {
		c.clearPtr()
	}
}

// clearPtrAll is the slice variant of clearPtrAny. Used when the
// proto-field's wire shape is repeated-handle and the C++ side
// adopts ownership of every element. Each element runs through
// the same type-assertion shortcut so the helper handles
// concrete-pointer slices, interface slices, and slices that mix
// nil and non-nil entries uniformly.
func clearPtrAll[T any](items []T) {
	for _, item := range items {
		clearPtrAny(item)
	}
}

// pbReader is a streaming protobuf decoder.
type pbReader struct {
	data []byte
	pos  int
}

func (r *pbReader) hasData() bool { return r.pos < len(r.data) }

func (r *pbReader) readVarint() uint64 {
	var v uint64
	var shift uint
	for r.pos < len(r.data) {
		b := r.data[r.pos]
		r.pos++
		v |= uint64(b&0x7f) << shift
		if b < 0x80 {
			return v
		}
		shift += 7
	}
	return v
}

func (r *pbReader) next() (field, wireType uint32, ok bool) {
	if !r.hasData() {
		return 0, 0, false
	}
	tag := r.readVarint()
	return uint32(tag >> 3), uint32(tag & 7), true
}

func (r *pbReader) readString() string {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	s := string(r.data[r.pos : r.pos+n])
	r.pos += n
	return s
}

func (r *pbReader) readBytes() []byte {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	b := make([]byte, n)
	copy(b, r.data[r.pos:r.pos+n])
	r.pos += n
	return b
}

func (r *pbReader) readBool() bool {
	return r.readVarint() != 0
}

func (r *pbReader) readInt32() int32 {
	return int32(r.readVarint())
}

func (r *pbReader) readInt64() int64 {
	return int64(r.readVarint())
}

func (r *pbReader) readUint32() uint32 {
	return uint32(r.readVarint())
}

func (r *pbReader) readUint64() uint64 {
	return r.readVarint()
}

func (r *pbReader) readFloat() float32 {
	if r.pos+4 > len(r.data) {
		r.pos = len(r.data)
		return 0
	}
	v := binary.LittleEndian.Uint32(r.data[r.pos : r.pos+4])
	r.pos += 4
	return math.Float32frombits(v)
}

func (r *pbReader) readDouble() float64 {
	if r.pos+8 > len(r.data) {
		r.pos = len(r.data)
		return 0
	}
	v := binary.LittleEndian.Uint64(r.data[r.pos : r.pos+8])
	r.pos += 8
	return math.Float64frombits(v)
}

func (r *pbReader) readSubmessage() *pbReader {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	sub := &pbReader{data: r.data[r.pos : r.pos+n]}
	r.pos += n
	return sub
}

func (r *pbReader) skip(wireType uint32) {
	switch wireType {
	case 0: // varint
		r.readVarint()
	case 1: // 64-bit
		r.pos += 8
	case 2: // length-delimited
		n := int(r.readVarint())
		r.pos += n
	case 5: // 32-bit
		r.pos += 4
	}
	if r.pos > len(r.data) {
		r.pos = len(r.data)
	}
}

// pbExtractError scans a response for field 15 (error string).
func pbExtractError(resp []byte) error {
	r := &pbReader{data: resp}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 15 {
			return errors.New(r.readString())
		}
		r.skip(w)
	}
	return nil
}

// readHandlePtr reads the ptr from a response. Handles two patterns:
// 1. Direct varint: field 1, wireType 0 → read varint directly
// 2. Submessage: field 1, wireType 2 → read submessage, then field 1 varint inside
func readHandlePtr(data []byte) uint64 {
	r := &pbReader{data: data}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 1 {
			if w == 0 {
				// Direct varint (constructor pattern)
				return r.readVarint()
			}
			if w == 2 {
				// Submessage (write_handle pattern)
				sub := r.readSubmessage()
				for sf, sw, sok := sub.next(); sok; sf, sw, sok = sub.next() {
					if sf == 1 && sw == 0 {
						return sub.readVarint()
					}
					sub.skip(sw)
				}
			}
			return 0
		}
		r.skip(w)
	}
	return 0
}

// readPtrAtField returns the handle pointer encoded at response field f.
// f == 1 takes the fast path via readHandlePtr (which already handles
// both the direct-varint constructor shape and the submessage write_handle
// shape); other fields are walked once to find the correct submessage.
// Returns 0 if the field is not present, which is the standard "absent
// handle" sentinel — callers translate that to (nil, nil).
func readPtrAtField(resp []byte, f uint32) uint64 {
	if f == 1 {
		return readHandlePtr(resp)
	}
	pr := &pbReader{data: resp}
	for ff, w, ok := pr.next(); ok; ff, w, ok = pr.next() {
		if ff == f {
			if w == 2 {
				sub := pr.readSubmessage()
				return readHandlePtr(sub.data)
			}
			return 0
		}
		pr.skip(w)
	}
	return 0
}

// decodeChildHandle is the standard accessor-return shape. It reads
// the handle pointer at field f, returns nil for missing/zero, and
// otherwise constructs the child via ctor and pins the parent (owner)
// onto it via setKeepAlive when owner is non-nil. Constructor-style
// callers (free functions) pass owner=nil; accessors pass the
// receiver. The child must already implement the unexported keepAlive
// interface, which every generated handle struct does.
func decodeChildHandle[T any](resp []byte, field uint32, owner any, ctor func(uint64) *T) *T {
	ptr := readPtrAtField(resp, field)
	if ptr == 0 {
		return nil
	}
	child := ctor(ptr)
	if owner != nil {
		if ka, ok := any(child).(interface{ setKeepAlive(any) }); ok {
			ka.setKeepAlive(owner)
		}
	}
	return child
}

// decodeAbstractAs is the abstract-return counterpart of
// decodeChildHandle: read field f, look up the runtime concrete type
// via resolveAbstractHandle, type-assert to I, attach keepAlive when
// owner is non-nil. ifaceName is only used in the error message when
// the runtime type does not satisfy I (which is a real bug, not a
// "missing field" condition).
func decodeAbstractAs[I any](resp []byte, field uint32, owner any, ifaceName string) (I, error) {
	var z I
	ptr := readPtrAtField(resp, field)
	if ptr == 0 {
		return z, nil
	}
	resolved, err := resolveAbstractHandle(ptr)
	if err != nil {
		return z, err
	}
	if v, ok := resolved.(I); ok {
		if owner != nil {
			if ka, okKA := any(v).(interface{ setKeepAlive(any) }); okKA {
				ka.setKeepAlive(owner)
			}
		}
		return v, nil
	}
	return z, fmt.Errorf("resolved type %T does not implement %s", resolved, ifaceName)
}

// readScalarAtField walks resp once for field f and reads the value via
// the read closure. Missing field returns the zero value. The closure is
// always one of (*pbReader).readBool / readInt32 / readInt64 / readUint32
// / readUint64 / readFloat / readDouble / readString / readBytes - small
// values, but they fold the per-method scan-and-read loop into one call
// site.
func readScalarAtField[T any](resp []byte, f uint32, read func(*pbReader) T) T {
	var z T
	pr := &pbReader{data: resp}
	for ff, w, ok := pr.next(); ok; ff, w, ok = pr.next() {
		if ff == f {
			return read(pr)
		}
		pr.skip(w)
	}
	return z
}

// factoryFor curries a typed constructor (newXNoFinalizer) into the
// untyped factory shape stored in cppTypeFactories. Without it the
// generated cppTypeToGoType map had to repeat
//
//	"googlesql::Foo": func(ptr uint64) any { return newFooNoFinalizer(ptr) }
//
// per concrete type — ~1,400 structurally-identical closures.
func factoryFor[T any](ctor func(uint64) *T) func(uint64) any {
	return func(ptr uint64) any { return ctor(ptr) }
}

// enumString backs the per-enum String() methods. Generated code emits
// parallel _vals_<E> []int32 and _names_<E> []string slices keyed in
// canonical order; this helper does a linear scan and falls back to
// the decimal form for values that aren't in the table (forward
// compatibility when new values land before regeneration).
func enumString(v int32, vals []int32, names []string) string {
	for i, x := range vals {
		if x == v {
			return names[i]
		}
	}
	return strconv.Itoa(int(v))
}

var _ = errors.New
var _ = binary.LittleEndian
var _ = fmt.Errorf
var _ = math.Float32bits
var _ = strconv.Itoa

// Module is the bridge handle. It wraps the wasm2go-transpiled module
// (*base.Module) and serialises every entry on m.mu.
//
// Reentrant callbacks — a host-import callback whose handler needs
// to make further calls back into the transpiled module — are
// supported by releasing m.mu around the user handler in
// handleCallback.
//
// Safety rests on a single structural property: every path that
// touches transpiled module state goes through m.invoke, and
// m.invoke holds m.mu for the entire duration of its call. The
// release window in handleCallback simply lets another m.invoke
// grab the mutex and run as a fully nested top-level call — same
// goroutine via the user handler, different goroutine via an
// unrelated caller, it doesn't matter. Either way the nested call
// enters, balances its own state changes, and exits before the
// outer call resumes, so the outer call never observes a mid-flight
// inner call.
type Module struct {
	// mu serialises every entry into the transpiled module (invoke +
	// nested re-entry from inside a callback handler).
	mu sync.Mutex
	g  *base.Module
	// cbMu guards callbacks and nextCBID. RWMutex because lookup in
	// handleCallback is hot (every host-import dispatch) while
	// Register/Unregister are rare (typically once per lifetime of a
	// registered Go-side handler). Held only for the brief map op;
	// never held while running user code or the transpiled module,
	// so it never participates in the m.mu -> transpiled-module ->
	// handleCallback chain and cannot deadlock against it.
	cbMu      sync.RWMutex
	callbacks map[int32]CallbackHandler
	nextCBID  int32
	// cbDesc is the reusable guest-memory result descriptor for callback
	// returns on a memory64 module (see encodeCallbackResult); 0 until
	// first use, and never touched on wasm32.
	cbDesc wptr
}

// wptr is the guest pointer width: int32 for a wasm32 module, int64
// for a memory64 (wasm64) one. Every pointer or length that crosses
// the bridge boundary is a wptr; the transpiled wasm2go package's
// export/import signatures use the same width, so the two packages
// stay in lock-step from the one substitution the generator makes.
type wptr = int32

var (
	globalModule *Module
	initOnce     sync.Once
	initErr      error
)

// CallbackHandler is implemented by Go types that need to be called from C++.
// The type is always defined (the Module struct references it); the
// registration/dispatch machinery is only emitted when the wasm imports
// wasmify.callback_invoke.
type CallbackHandler interface {
	HandleCallback(methodID int32, req []byte) ([]byte, error)
}

// Options configure the module the generated API runs on. The zero
// value is what Init uses: the default WASI implementation (the host
// filesystem, environment and stdio), the engine's own initial memory
// reservation, and its wasm32 4 GiB ceiling.
type Options struct {
	// WASI replaces the wasi_snapshot_preview1 implementation the guest
	// runs against. base.DefaultWASI() returns the default one, whose
	// setters scope the filesystem to a directory (or an arbitrary
	// base.FS), replace the environment and redirect stdio; any
	// implementation of the interface will do. nil keeps the default.
	WASI base.Wasi_snapshot_preview1Imports

	// MemoryReserveBytes pre-reserves linear memory. A guest that grows
	// to a size known up front — loading a large model or data file —
	// otherwise reallocates and copies the whole linear memory as it
	// goes. Zero keeps the engine's default headroom.
	MemoryReserveBytes int

	// MaxMemoryBytes caps linear-memory growth, so a workload bigger
	// than expected fails inside the guest (memory.grow returns -1)
	// instead of growing the host process. Zero keeps the engine's own
	// ceiling.
	MaxMemoryBytes uint64
}

// Init initializes the global module with the default Options. Must be
// called before any API use. Safe to call multiple times (uses
// sync.Once).
func Init() error { return InitWith(Options{}) }

// InitWith initializes the global module with opts. Like Init it runs at
// most once per process: the module owns one linear memory and one C
// heap, so there is exactly one instance and the first initialization
// wins. A later call — with any Options — returns that instance's
// initialization result without reconfiguring it.
func InitWith(opts Options) error {
	initOnce.Do(func() {
		initErr = initModule(opts)
	})
	return initErr
}

// module returns the initialized global module. Panics if Init was not
// called.
func module() *Module {
	if globalModule == nil {
		panic("wasmify: Init() must be called before using any API")
	}
	return globalModule
}

// Instance returns the transpiled module the global API runs on, or nil
// before initialization.
//
// It exists for base.AccessMemory, which is the only safe way to read or
// write linear memory from a goroutine other than the one running a call
// — an interrupt flag an embedder raises while a long call is in flight,
// a progress word it polls. Everything else should go through the
// generated API: calling into the module directly bypasses the lock that
// serialises entries and the C stack would be shared with the call in
// progress.
func Instance() *base.Module {
	if globalModule == nil {
		return nil
	}
	return globalModule.g
}

func initModule(opts Options) (retErr error) {
	m := &Module{}
	env := envStubs{m: m}
	wm := wasmifyStubs{m: m}
	wasi := opts.WASI
	if wasi == nil {
		wasi = base.DefaultWASI()
	}
	if opts.MemoryReserveBytes > 0 {
		m.g = wasm2go.NewWithWASIReserve(wasi, env, wm, opts.MemoryReserveBytes)
	} else {
		m.g = wasm2go.NewWithWASI(wasi, env, wm)
	}
	if opts.MaxMemoryBytes > 0 {
		wasm2go.SetMaxMemory(m.g, opts.MaxMemoryBytes)
	}
	// Set globalModule eagerly so the rest of the API can run even if
	// _initialize panics partway through C++ static-initializer code.
	globalModule = m
	defer func() {
		if r := recover(); r != nil {
			retErr = fmt.Errorf("init panicked: %v", r)
		}
	}()
	wasm2go.Initialize(m.g)
	_ = wasm2go.WasmInit(m.g)
	return nil
}

// invoke serializes req into wasm memory, runs the per-export caller
// (wasm2go.Inv_<svc>_<mt>), and unpacks the response via decodeResult.
// call is the trap-safe per-export entry point: it snapshots and
// restores the mutable wasm globals so a mid-call panic does not leak
// an abandoned C++ activation frame.
func (m *Module) invoke(serviceID, methodID int32, req []byte, call func(*base.Module, wptr, wptr) (int64, error)) ([]byte, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	var reqPtr, reqLen wptr
	if len(req) > 0 {
		reqPtr = wasm2go.WasmAlloc(m.g, wptr(len(req)))
		reqLen = wptr(len(req))
		// Free reqPtr unconditionally on return so the request
		// buffer never lingers in wasm memory when the call traps
		// or the early-exit branches below fire. Guard against
		// the WasmAlloc-returned-zero case: free(NULL) is a
		// dlmalloc no-op but C++ allocators are less consistent.
		if reqPtr != 0 {
			defer wasm2go.WasmFree(m.g, reqPtr)
		}
		copy(wasm2go.Memory(m.g)[wptrOff(reqPtr):], req)
	}
	packed, err := call(m.g, reqPtr, reqLen)
	if err != nil {
		return nil, err
	}
	respPtr, respLen := decodeResult(m.g, packed)
	if respLen == 0 {
		return nil, nil
	}
	mem := wasm2go.Memory(m.g)
	out := make([]byte, respLen)
	copy(out, mem[respPtr:respPtr+respLen])
	wasm2go.WasmFree(m.g, wptr(respPtr))
	return out, nil
}

// resolveTypeName calls the C++ bridge to get the runtime type name of
// the object at ptr. Returns a fully qualified C++ class name.
func (m *Module) resolveTypeName(ptr uint64) (string, error) {
	buf := pbAppendUint64(pbNewBuf(), 1, ptr)
	m.mu.Lock()
	defer m.mu.Unlock()
	reqPtr := wasm2go.WasmAlloc(m.g, wptr(len(buf)))
	copy(wasm2go.Memory(m.g)[wptrOff(reqPtr):], buf)
	packed := wasm2go.WasmifyGetTypeName(m.g, reqPtr, wptr(len(buf)))
	respPtr, respLen := decodeResult(m.g, packed)
	defer wasm2go.WasmFree(m.g, reqPtr)
	if respLen == 0 {
		return "", nil
	}
	resp := make([]byte, respLen)
	copy(resp, wasm2go.Memory(m.g)[respPtr:respPtr+respLen])
	defer wasm2go.WasmFree(m.g, wptr(respPtr))
	if e := pbExtractError(resp); e != nil {
		return "", e
	}
	r := &pbReader{data: resp}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 1 {
			return r.readString(), nil
		}
		r.skip(w)
	}
	return "", nil
}

// invokeMethod fans the wasm call out into the runtime, then folds in
// the (very common) pbExtractError check on the response. call is the
// per-export wasm2go.Inv_<svc>_<mt> entry point.
func invokeMethod(svc, mid int32, req []byte, call func(*base.Module, wptr, wptr) (int64, error)) ([]byte, error) {
	resp, err := module().invoke(svc, mid, req, call)
	if err != nil {
		return nil, err
	}
	if e := pbExtractError(resp); e != nil {
		return nil, e
	}
	return resp, nil
}

// wptrOff widens a guest pointer to an unsigned slice offset. wasm32
// pointers are UNSIGNED i32s: past the 2 GiB line the bit pattern is
// negative in Go, so a signed slice index would panic.
func wptrOff(p wptr) uint64 {
	return uint64(uint32(p))
}

func decodeResult(_ *base.Module, packed int64) (uint64, uint64) {
	return uint64(packed) >> 32, uint64(packed) & 0xFFFFFFFF
}

func encodeCallbackResult(m *Module, resp []byte) int64 {
	ptr := wasm2go.WasmAlloc(m.g, wptr(len(resp)))
	copy(wasm2go.Memory(m.g)[wptrOff(ptr):], resp)
	return int64(ptr)<<32 | int64(len(resp))
}

// envStubs implements wasm2go/base.EnvImports — the host side of the
// wasm "env" imports. The per-method definitions are emitted by the
// generator (generateEnvStubs) since the import set is module-specific.
type envStubs struct{ m *Module }

// RegisterCallback registers a Go callback handler and returns its ID.
// Safe to call concurrently with other Register/Unregister/callback
// dispatch calls.
func RegisterCallback(handler CallbackHandler) int32 {
	m := module()
	m.cbMu.Lock()
	defer m.cbMu.Unlock()
	if m.callbacks == nil {
		m.callbacks = make(map[int32]CallbackHandler)
	}
	m.nextCBID++
	id := m.nextCBID
	m.callbacks[id] = handler
	return id
}

// UnregisterCallback removes a previously registered callback handler.
// Safe to call concurrently with other Register/Unregister/callback
// dispatch calls.
func UnregisterCallback(id int32) {
	m := module()
	m.cbMu.Lock()
	delete(m.callbacks, id)
	m.cbMu.Unlock()
}

func (m *Module) handleCallback(callbackID, methodID int32, reqPtr, reqLen wptr) int64 {
	m.cbMu.RLock()
	handler, ok := m.callbacks[callbackID]
	m.cbMu.RUnlock()
	if !ok {
		return 0
	}
	mem := wasm2go.Memory(m.g)
	var req []byte
	if reqLen > 0 {
		buf := make([]byte, reqLen)
		copy(buf, mem[wptrOff(reqPtr):wptrOff(reqPtr)+uint64(reqLen)])
		req = buf
	}
	// Release m.mu around the user handler so that nested calls
	// back into the transpiled module can re-acquire it without
	// deadlocking. The IIFE + defer guarantees Lock is retaken even
	// if the handler panics, so the outer invoke's defer
	// m.mu.Unlock() always sees a held mutex.
	var resp []byte
	var err error
	func() {
		m.mu.Unlock()
		defer m.mu.Lock()
		resp, err = handler.HandleCallback(methodID, req)
	}()
	if err != nil {
		resp = pbAppendString(nil, 15, err.Error())
	}
	if len(resp) == 0 {
		return 0
	}
	return encodeCallbackResult(m, resp)
}

// wasmifyStubs implements wasm2go/base.WasmifyImports: the single
// callback_invoke entry point that the C++ bridge calls back into.
type wasmifyStubs struct{ m *Module }

func (h wasmifyStubs) Callback_invoke(_ *base.Module, callbackID, methodID int32, reqPtr, reqLen wptr) int64 {
	return h.m.handleCallback(callbackID, methodID, reqPtr, reqLen)
}

func (h envStubs) Dlerror(m *base.Module) int32                    { return 0 }
func (h envStubs) Dlopen(m *base.Module, l0 int32, l1 int32) int32 { return 0 }
func (h envStubs) Dlsym(m *base.Module, l0 int32, l1 int32) int32  { return 0 }
func (h envStubs) Getpid(m *base.Module) int32                     { return 0 }
func (h envStubs) X__cxa_allocate_exception(m *base.Module, l0 int32) int32 {
	if l0 == 0 {
		l0 = 64
	}
	return wasm2go.WasmAlloc(m, l0)
}
func (h envStubs) X__cxa_throw(m *base.Module, l0 int32, l1 int32, l2 int32) {
	panic("wasm: C++ exception thrown")
}

var _ = fmt.Errorf
var _ = sort.Search

// cppTypeNames / cppTypeFactories: parallel sorted slices replacing
// the old cppTypeToGoType map literal. Looked up via sort.Search.
var cppTypeNames = []string{}

var cppTypeFactories = []func(uint64) any{}

// resolveAbstractHandle queries the C++ runtime for the actual type of the
// object at ptr and returns the appropriate concrete Go handle type.
func resolveAbstractHandle(ptr uint64) (any, error) {
	typeName, err := module().resolveTypeName(ptr)
	if err != nil {
		return nil, fmt.Errorf("resolveTypeName: %w", err)
	}
	i := sort.SearchStrings(cppTypeNames, typeName)
	if i < len(cppTypeNames) && cppTypeNames[i] == typeName {
		return cppTypeFactories[i](ptr), nil
	}
	return nil, fmt.Errorf("unknown C++ type %q for ptr 0x%x", typeName, ptr)
}

var _ = errors.New
var _ = fmt.Errorf
var _ = runtime.SetFinalizer

func PyAsyncExcAddr(h uint64) (uint32, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	resp, err := invokeMethod(0, 0, buf, wasm2go.Inv_0_0)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readUint32), nil
}

// callable(*args, **kwargs). args is a node list, kwargs a kwargs list.
func PyCall(h uint64, callable uint64, args string, argsLen uint32, kwargs string, kwargsLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, callable)
	buf = pbAppendString(buf, 3, args)
	buf = pbAppendUint64(buf, 4, uint64(argsLen))
	buf = pbAppendString(buf, 5, kwargs)
	buf = pbAppendUint64(buf, 6, uint64(kwargsLen))
	resp, err := invokeMethod(0, 1, buf, wasm2go.Inv_0_1)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// getattr(obj, name)(*args, **kwargs) in one crossing.
func PyCallMethod(h uint64, obj uint64, name string, nameLen uint32, args string, argsLen uint32, kwargs string, kwargsLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendString(buf, 3, name)
	buf = pbAppendUint64(buf, 4, uint64(nameLen))
	buf = pbAppendString(buf, 5, args)
	buf = pbAppendUint64(buf, 6, uint64(argsLen))
	buf = pbAppendString(buf, 7, kwargs)
	buf = pbAppendUint64(buf, 8, uint64(kwargsLen))
	resp, err := invokeMethod(0, 2, buf, wasm2go.Inv_0_2)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Destroy the interpreter: drop every registry pin, then finalize the
// runtime.
func PyClose(h uint64) error {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	_, err := invokeMethod(0, 3, buf, wasm2go.Inv_0_3)
	return err
}

// key in obj. ok: u8.
func PyContains(h uint64, obj uint64, key string, keyLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendString(buf, 3, key)
	buf = pbAppendUint64(buf, 4, uint64(keyLen))
	resp, err := invokeMethod(0, 4, buf, wasm2go.Inv_0_4)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func PyDelitem(h uint64, obj uint64, key string, keyLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendString(buf, 3, key)
	buf = pbAppendUint64(buf, 4, uint64(keyLen))
	resp, err := invokeMethod(0, 5, buf, wasm2go.Inv_0_5)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// dict operations. py_dict_get ok: u8 exists + node (none when absent — a
// missing key is not an error). py_dict_keys / py_dict_values ok: node list.
// py_dict_items ok: node list of 2 * len nodes (key, value, key, value...).
func PyDictGet(h uint64, obj uint64, key string, keyLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendString(buf, 3, key)
	buf = pbAppendUint64(buf, 4, uint64(keyLen))
	resp, err := invokeMethod(0, 6, buf, wasm2go.Inv_0_6)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func PyDictItems(h uint64, obj uint64) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	resp, err := invokeMethod(0, 7, buf, wasm2go.Inv_0_7)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func PyDictKeys(h uint64, obj uint64) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	resp, err := invokeMethod(0, 8, buf, wasm2go.Inv_0_8)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func PyDictValues(h uint64, obj uint64) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	resp, err := invokeMethod(0, 9, buf, wasm2go.Inv_0_9)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Evaluate `src` in the persistent __main__ namespace (REPL-like state
// persistence). ok payload:
//
//	result:node stdout:(u32 len + bytes) stderr:(u32 len + bytes)
//
// result is the value of the LAST statement when it is an expression
// statement, none otherwise. A raised / exit envelope is followed by the same
// stdout/stderr pair — what the code printed before failing is still
// delivered.
func PyEval(h uint64, src string) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendString(buf, 2, src)
	resp, err := invokeMethod(0, 10, buf, wasm2go.Inv_0_10)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// ---- Interruption support ------------------------------------------------
//
// Mirrors PyThreadState_SetAsyncExc() done as plain memory writes, so a host
// watchdog goroutine can raise KeyboardInterrupt in a running interpreter
// WITHOUT executing any wasm/C code on that instance (which would corrupt the
// shared linear-memory C stack). To interrupt, the host performs:
//
//	*(uint32_t *)py_async_exc_addr(h)   = py_keyboard_interrupt_obj(h);
//	atomic_or((uint32_t *)py_eval_breaker_addr(h), 8); // _PY_ASYNC_EXCEPTION_BIT
//
// CPython checks eval_breaker on every bytecode backward edge (3.9+), so it
// raises KeyboardInterrupt at the next loop iteration — including a pure
// `while True: pass`. PyExc_KeyboardInterrupt is immortal in 3.14, so storing
// it needs no refcount bookkeeping. Addresses are 32-bit linear-memory
// offsets (wasm32). The async-exception bit is the constant 8 (1u
// <
// <
// 3).
func PyEvalBreakerAddr(h uint64) (uint32, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	resp, err := invokeMethod(0, 11, buf, wasm2go.Inv_0_11)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readUint32), nil
}

// getattr / setattr. ok payload of py_setattr: empty.
func PyGetattr(h uint64, obj uint64, name string, nameLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendString(buf, 3, name)
	buf = pbAppendUint64(buf, 4, uint64(nameLen))
	resp, err := invokeMethod(0, 12, buf, wasm2go.Inv_0_12)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// obj[key], obj[key] = val, del obj[key]. key / val are single nodes. ok
// payload of py_setitem / py_delitem: empty.
func PyGetitem(h uint64, obj uint64, key string, keyLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendString(buf, 3, key)
	buf = pbAppendUint64(buf, 4, uint64(keyLen))
	resp, err := invokeMethod(0, 13, buf, wasm2go.Inv_0_13)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// import name. ok: node (the module).
func PyImport(h uint64, name string, nameLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendString(buf, 2, name)
	buf = pbAppendUint64(buf, 3, uint64(nameLen))
	resp, err := invokeMethod(0, 14, buf, wasm2go.Inv_0_14)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// isinstance(obj, cls). ok: u8.
func PyIsinstance(h uint64, obj uint64, cls uint64) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendUint64(buf, 3, cls)
	resp, err := invokeMethod(0, 15, buf, wasm2go.Inv_0_15)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// list(obj) — every element the object yields when iterated. ok: node list.
// Backs list / tuple / set contents and dict keys alike.
func PyIter(h uint64, obj uint64) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	resp, err := invokeMethod(0, 16, buf, wasm2go.Inv_0_16)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func PyKeyboardInterruptObj(h uint64) (uint32, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	resp, err := invokeMethod(0, 17, buf, wasm2go.Inv_0_17)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readUint32), nil
}

// len(obj). ok: i64.
func PyLen(h uint64, obj uint64) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	resp, err := invokeMethod(0, 18, buf, wasm2go.Inv_0_18)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// list.append(each of elems). ok payload: empty.
func PyListAppend(h uint64, obj uint64, elems string, elemsLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendString(buf, 3, elems)
	buf = pbAppendUint64(buf, 4, uint64(elemsLen))
	resp, err := invokeMethod(0, 19, buf, wasm2go.Inv_0_19)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Initialize the CPython runtime (isolated config) and return an opaque
// interpreter handle (0 on failure). Call once per wasm instance.
//
// `stdlib_dir` is the directory holding the Python standard library (the
// `Lib/` tree: encodings/, io.py, codecs.py, ...). It becomes the sole
// module search path. The isolated config ignores PYTHONPATH, so the host
// MUST pass this (the dir is reached through the runtime's WASI filesystem
// mount). Pass NULL/empty to fall back to CPython's default path discovery
// (usually fails in the sandbox — provide the path).
//
// The isolated config ignores the environment, with one deliberate
// exception: PYTHONVERBOSE in the guest environment turns on the import
// trace, and a failed initialisation reports the pending exception on
// stderr — the way to see why a runtime did not come up.
func PyNew(stdlibDir string) (uint64, error) {
	buf := pbNewBuf()
	buf = pbAppendString(buf, 1, stdlibDir)
	resp, err := invokeMethod(0, 20, buf, wasm2go.Inv_0_20)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readUint64), nil
}

func PyNewDict(h uint64, items string, itemsLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendString(buf, 2, items)
	buf = pbAppendUint64(buf, 3, uint64(itemsLen))
	resp, err := invokeMethod(0, 21, buf, wasm2go.Inv_0_21)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func PyNewFrozenset(h uint64, elems string, elemsLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendString(buf, 2, elems)
	buf = pbAppendUint64(buf, 3, uint64(elemsLen))
	resp, err := invokeMethod(0, 22, buf, wasm2go.Inv_0_22)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Materialise the host function bound under func_id as a Python builtin
// function named name (see "Python -> Go" above). ok: node (a function
// handle).
func PyNewFunction(h uint64, name string, nameLen uint32, funcId int32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendString(buf, 2, name)
	buf = pbAppendUint64(buf, 3, uint64(nameLen))
	buf = pbAppendInt32(buf, 4, funcId)
	resp, err := invokeMethod(0, 23, buf, wasm2go.Inv_0_23)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Materialise host data as a guest aggregate in one crossing. elems is a node
// list; items is a node list of 2 * n nodes (key, value, ...). ok: node.
func PyNewList(h uint64, elems string, elemsLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendString(buf, 2, elems)
	buf = pbAppendUint64(buf, 3, uint64(elemsLen))
	resp, err := invokeMethod(0, 24, buf, wasm2go.Inv_0_24)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func PyNewSet(h uint64, elems string, elemsLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendString(buf, 2, elems)
	buf = pbAppendUint64(buf, 3, uint64(elemsLen))
	resp, err := invokeMethod(0, 25, buf, wasm2go.Inv_0_25)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func PyNewTuple(h uint64, elems string, elemsLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendString(buf, 2, elems)
	buf = pbAppendUint64(buf, 3, uint64(elemsLen))
	resp, err := invokeMethod(0, 26, buf, wasm2go.Inv_0_26)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Release registry pins: ids is a packed array of u64 handles (one pin each).
// ok payload: empty.
func PyRelease(h uint64, ids string, idsLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendString(buf, 2, ids)
	buf = pbAppendUint64(buf, 3, uint64(idsLen))
	resp, err := invokeMethod(0, 27, buf, wasm2go.Inv_0_27)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func PyRepr(h uint64, obj uint64) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	resp, err := invokeMethod(0, 28, buf, wasm2go.Inv_0_28)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// set.add(val) / set.discard(val). ok payload: empty.
func PySetAdd(h uint64, obj uint64, val string, valLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendString(buf, 3, val)
	buf = pbAppendUint64(buf, 4, uint64(valLen))
	resp, err := invokeMethod(0, 29, buf, wasm2go.Inv_0_29)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func PySetDiscard(h uint64, obj uint64, val string, valLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendString(buf, 3, val)
	buf = pbAppendUint64(buf, 4, uint64(valLen))
	resp, err := invokeMethod(0, 30, buf, wasm2go.Inv_0_30)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Register the host callback id every Python -> Go call from this instance
// dispatches to (the wasmify callback_invoke callback_id).
func PySetGoDispatcher(h uint64, callbackId int32) error {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendInt32(buf, 2, callbackId)
	_, err := invokeMethod(0, 31, buf, wasm2go.Inv_0_31)
	return err
}

func PySetattr(h uint64, obj uint64, name string, nameLen uint32, val string, valLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendString(buf, 3, name)
	buf = pbAppendUint64(buf, 4, uint64(nameLen))
	buf = pbAppendString(buf, 5, val)
	buf = pbAppendUint64(buf, 6, uint64(valLen))
	resp, err := invokeMethod(0, 32, buf, wasm2go.Inv_0_32)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func PySetitem(h uint64, obj uint64, key string, keyLen uint32, val string, valLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	buf = pbAppendString(buf, 3, key)
	buf = pbAppendUint64(buf, 4, uint64(keyLen))
	buf = pbAppendString(buf, 5, val)
	buf = pbAppendUint64(buf, 6, uint64(valLen))
	resp, err := invokeMethod(0, 33, buf, wasm2go.Inv_0_33)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// str(obj) / repr(obj). ok: u32 len + UTF-8 bytes.
func PyStr(h uint64, obj uint64) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, h)
	buf = pbAppendUint64(buf, 2, obj)
	resp, err := invokeMethod(0, 34, buf, wasm2go.Inv_0_34)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}
